# Generated by Django 3.0.7 on 2020-06-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ethinicity',
            new_name='ethnicity',
        ),
    ]
