# Generated by Django 3.0.7 on 2020-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_category_talk'),
        ('jwt_auth', '0003_user_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='User', to='categories.Category'),
        ),
    ]
