# Generated by Django 3.0.7 on 2020-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_category_talk'),
        ('jwt_auth', '0004_auto_20200607_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='User', to='categories.Category'),
        ),
    ]
