# Generated by Django 3.0.7 on 2020-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200606_1453'),
        ('jwt_auth', '0009_auto_20200607_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ManyToManyField(blank=True, related_name='User', to='images.UserImage'),
        ),
    ]
