# Generated by Django 3.0.7 on 2020-06-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkimage',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_images', to='talks.Talk'),
        ),
    ]
