# Generated by Django 3.0.7 on 2020-06-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200606_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='talkImage',
        ),
    ]
