# Generated by Django 3.0.7 on 2020-06-08 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_auto_20200608_1024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_auto_20200608_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkimage',
            name='talk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='talk_images', to='talks.Talk'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
