# Generated by Django 3.0.7 on 2020-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='talk',
            field=models.ManyToManyField(related_name='baskets', to='talks.Talk'),
        ),
    ]
