# Generated by Django 3.0.7 on 2020-06-09 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='talk',
            field=models.ManyToManyField(blank=True, related_name='basket', to='talks.Talk'),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_basket', to=settings.AUTH_USER_MODEL),
        ),
    ]
