# Generated by Django 3.0.7 on 2020-06-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_basket_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='image',
        ),
        migrations.AddField(
            model_name='basket',
            name='summary',
            field=models.CharField(default='summary', max_length=200),
            preserve_default=False,
        ),
    ]
