# Generated by Django 3.0.7 on 2020-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
        ('baskets', '0002_auto_20200609_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basket',
            name='talk',
            field=models.ManyToManyField(blank=True, related_name='basket', to='talks.Talk'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
