# Generated by Django 3.0.7 on 2020-06-08 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baskets', '0003_auto_20200608_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='talk',
        ),
        migrations.AddField(
            model_name='basket',
            name='talk',
            field=models.ManyToManyField(related_name='baskets', to='talks.Talk'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_basket', to=settings.AUTH_USER_MODEL),
        ),
    ]
