# Generated by Django 3.0.7 on 2020-06-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_talk_price'),
        ('baskets', '0004_basket_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='talk',
        ),
        migrations.AddField(
            model_name='basket',
            name='talk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='talks.Talk'),
            preserve_default=False,
        ),
    ]
