# Generated by Django 3.0.7 on 2020-06-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200605_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='label',
            new_name='category',
        ),
    ]
