# Generated by Django 3.0.7 on 2020-06-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_talk_category'),
        ('categories', '0008_auto_20200607_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='talk',
        ),
        migrations.AddField(
            model_name='category',
            name='talk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='talks.Talk'),
            preserve_default=False,
        ),
    ]
