# Generated by Django 3.0.7 on 2020-06-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_talk_category'),
        ('categories', '0009_auto_20200607_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='talk',
        ),
        migrations.AddField(
            model_name='category',
            name='talk',
            field=models.ManyToManyField(related_name='categories', to='talks.Talk'),
        ),
    ]
