# Generated by Django 3.0.7 on 2020-06-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_c',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_d',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
