# Generated by Django 3.0.7 on 2020-06-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='category',
            new_name='categories',
        ),
    ]
