# Generated by Django 3.0.7 on 2020-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_category_talk'),
        ('talks', '0002_talk_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='Talk', to='categories.Category'),
        ),
    ]
