# Generated by Django 3.0.7 on 2020-06-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20200608_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='image',
        ),
    ]
