# Generated by Django 3.0.7 on 2020-06-08 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0003_remove_talk_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_talks', to=settings.AUTH_USER_MODEL),
        ),
    ]
