# Generated by Django 3.0.7 on 2020-06-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200606_1453'),
        ('talks', '0003_talk_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='image',
        ),
        migrations.AddField(
            model_name='talk',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='Talk', to='images.TalkImage'),
        ),
    ]
